name: package

on:
  push:
    branches:
      - master
    
jobs:
  osx:
    name: build on macOS X
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git submodule sync --recursive
          git submodule update --recursive
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.1
      - name: build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build
          ls ./dist
      - name: build electron
        run: |
          yarn
          yarn build
      - name: list
        run: ls ./release
      # - name: upload dmg
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release
      #     path: ./release/-beta.dmg
      # - name: upload zip
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release
      #     path: ./release/-1.0.0-beta-mac.zip

  linux:
    name: build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git submodule sync --recursive
          git submodule update --recursive
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.1
      - name: build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build
          ls ./dist
      - name: build electron
        run: |
          yarn
          yarn build
      - name: list release
        run: ls ./release
      # - name: upload AppImage
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release
      #     path: ./release/HexFonts-1.0.0-beta.AppImage
      # - name: upload snap
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release
      #     path: ./release/h3xfonts_1.0.0-beta_amd64.snap
      # - name: upload tarball
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release
      #     path: ./release/h3xfonts-1.0.0-beta.tar.gz
      # - name: upload changelog
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release
      #     path: ./CHANGELOG.md
        
  # release:
  #   name: Release to Github
  #   needs: [osx, linux]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: release
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         body_path: ./release/CHANGELOG.md
  #         draft: true
  #         files: |
  #           ./release/HexFonts-1.0.0-beta-mac.zip
  #           ./release/HexFonts-1.0.0-beta.dmg
  #           ./release/HexFonts-1.0.0-beta.AppImage
  #           ./release/h3xfonts-1.0.0-beta.tar.gz
  #           ./release/h3xfonts_1.0.0-beta_amd64.snap
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}