name: package

on:
  push:
    tags:
      - 'v*.*-*'
    
jobs:
  osx:
    name: build on macOS X
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.2
      - name: build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build
      - name: build electron
        run: |
          yarn
          yarn build
      - name: list
        run: ls ./release
      - name: upload dmg
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: ./release/Covid19 MM-2.0.0.dmg
      - name: upload zip
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: ./release/Covid19 MM-2.0.0-mac.zip

  linux:
    name: build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.2
      - name: build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build
      - name: build electron
        run: |
          yarn
          yarn build
      - name: list
        run: ls ./release
      - name: upload AppImage
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: ./release/Covid19 MM-2.0.0.AppImage
      - name: upload snap
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: ./release/covidapi-client_2.0.0_amd64.snap
      - name: upload tarball
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: ./release/covidapi-client-2.0.0.tar.gz
      # - name: upload changelog
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release
      #     path: ./CHANGELOG.md
        
  windows:
    name: build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.2
      - name: build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build
      - name: build electron
        run: |
          yarn
          yarn build
      - name: list
        run: ls ./release 
        shell: pwsh
      - name: upload exe
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: ./release/Covid19 MM Setup 2.0.0.exe
      - name: upload zip
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: ./release/Covid19 MM-2.0.0-win.zip

  release:
    name: Release to Github
    needs: [osx, linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v1
        with:
          name: release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ./release/Covid19 MM Setup 2.0.0.exe
            ./release/Covid19 MM-2.0.0-win.zip
            ./release/Covid19 MM-2.0.0.AppImage
            ./release/covidapi-client_2.0.0_amd64.snap
            ./release/covidapi-client-2.0.0.tar.gz
            ./release/Covid19 MM-2.0.0.dmg
            ./release/Covid19 MM-2.0.0-mac.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}